import Head from "next/head";
import Image from "next/image";
import { getAllProducts } from "../lib/shopify";
import Link from "next/link";
import { Navigation } from "../components/navigation";
import { Footer } from "../components/footer";
import { CartContext } from "../context/CartContext";
import { useContext } from "react";

export default function CartPage() {
  const { cart } = useContext(CartContext);
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navigation />

      <main>
        <div className="bg-white">
          <div className="max-w-2xl mx-auto py-16 px-4 sm:py-24 sm:px-6 lg:px-0">
            <h1 className="text-3xl font-extrabold text-center tracking-tight text-gray-900 sm:text-4xl">
              Shopping Cart
            </h1>

           
              <section aria-labelledby="cart-heading">
                <h2 id="cart-heading" className="sr-only">
                  Items in your shopping cart
                </h2>

                <ul
                  role="list"
                  className="border-t border-b border-gray-200 divide-y divide-gray-200"
                >
                  {cart.lines &&
                    cart.lines.edges.map(({ node }) => (
                      <li key={node.id} className="flex py-6">
                        <div className="flex-shrink-0">
                          <Image
                            src={node.merchandise.image.originalSrc}
                            className="rounded-md object-center object-cover"
                            height="150"
                            width="150"
                            alt={node.merchandise.title}
                          />
                        </div>

                        <div className="ml-4 flex-1 flex flex-col sm:ml-6">
                          <div>
                            <div className="flex justify-between">
                              <h4 className="text-sm relative">
                              
                                  <a>
                                    <span className="absolute inset-0" />
                                    {node.merchandise.product.title}
                                    <br /> {node.merchandise.title}
                                  </a>
                              </h4>
                              <p className="ml-4 text-sm font-medium text-gray-900">
                                {node.merchandise.priceV2.amount}{" "}
                                {node.merchandise.priceV2.currencyCode}
                              </p>
                            </div>
                          </div>
                        </div>
                      </li>
                    ))}
                </ul>
              </section>
              {cart.estimatedCost &&
             
              <section aria-labelledby="summary-heading" className="mt-10 h-full">
                <h2 id="summary-heading" className="sr-only">
                  Order summary
                </h2>

                <div>
                  <dl className="space-y-4">
                    <div className="flex items-center justify-between">
                      <dt className="text-base font-medium text-gray-900">
                        Subtotal
                      </dt>
                      <dd className="ml-4 text-base font-medium text-gray-900">
                        {cart.estimatedCost.totalAmount.amount}{" "}
                        {cart.estimatedCost.totalAmount.currencyCode}
                      </dd>
                    </div>
                  </dl>
                  <p className="mt-1 text-sm text-gray-500">
                    Shipping and taxes will be calculated at checkout.
                  </p>
                </div>

                <div className="mt-10">
                  <a
                    href={cart.checkoutUrl}
                    target="_blank"
                    rel="noreferrer"
                    className="w-full bg-indigo-600 border border-transparent rounded-md shadow-sm py-3 px-4 text-base font-medium text-white hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-offset-gray-50 focus:ring-indigo-500"
                  >
                    Checkout
                  </a>
                </div>
              </section>
}
          </div>
        </div>
      </main>

      <Footer />
    </div>
  );
}
