import Head from "next/head";
import Image from "next/image";
import { getAllProducts } from "../lib/shopify";
import Link from "next/link";
import { Navigation } from "../components/navigation";
import { Footer } from "../components/footer";

export async function getStaticProps() {
  let productsData = await getAllProducts();
  return {
    props: { productsData },
    // Next.js will attempt to re-generate the page:
    // - When a request comes in
    // - At most once every 5 seconds
    revalidate: 5,
  };
}

export default function Home({ productsData }) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navigation />

      <main>
        {/* Trending products */}
        <section aria-labelledby="trending-heading" className="bg-white">
          <div className="py-16 sm:py-24 lg:max-w-7xl lg:mx-auto lg:py-32 lg:px-8">
            <div className="px-4 flex items-center justify-between sm:px-6 lg:px-0">
              <h2
                id="trending-heading"
                className="text-2xl font-extrabold tracking-tight text-gray-900"
              >
                Trending products
              </h2>
            </div>

            <div className="mt-8 relative">
              <div className="relative w-full overflow-x-auto">
                <ul
                  role="list"
                  className="mx-4 inline-flex space-x-8 sm:mx-6 lg:mx-0 lg:space-x-0 lg:grid lg:grid-cols-4 lg:gap-x-8"
                >
                  {productsData.map(({ node }) => (
                    <li
                      key={node.id}
                      className="w-64 inline-flex flex-col text-center lg:w-auto"
                    >
                      <div className="group relative">
                        <div className="w-full bg-gray-200 rounded-md overflow-hidden aspect-w-1 aspect-h-1">
                          <Image
                            alt={node.title}
                            src={node.images.edges[0].node.originalSrc}
                            height="500"
                            width="400"
                            quality={100}
                            className="w-full h-full object-center object-cover group-hover:opacity-75"
                          />
                        </div>
                        <div className="mt-6">
                          <h3 className="mt-1 font-semibold text-gray-900">
                            <Link href={`/product/${node.handle}`}>
                              <a>
                                <span className="absolute inset-0" />
                                {node.title}
                              </a>
                            </Link>
                          </h3>
                          <p className="mt-1 text-gray-900">
                            {node.priceRange.minVariantPrice.amount}{" "}
                            {node.priceRange.minVariantPrice.currencyCode}
                          </p>
                        </div>
                      </div>
                    </li>
                  ))}
                </ul>
              </div>
            </div>
          </div>
        </section>
      </main>

      <Footer />
    </div>
  );
}
